version: "3"

networks:
  app-network:
    driver: bridge

volumes:
  userdata:
  postdata:

services:
  user-db:
    container_name: docker-database-user
    image: postgres:12
    restart: always
    env_file:
      - .env.production
    ports:
      - 5433:5432
    networks:
      - app-network
    volumes:
      - userdata:/var/lib/postgresql/data

  post-db:
    container_name: docker-database-post
    image: postgres:12
    restart: always
    env_file:
      - .env.production
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - postdata:/var/lib/postgresql/data

  user-api:
    container_name: api-user
    build:
      dockerfile: Dockerfile
      context: ./user
    ports:
      - 8081:8080
    networks:
      - app-network
    env_file:
      - .env.production
    depends_on:
      - user-db

  post-api:
    container_name: api-post
    build:
      dockerfile: Dockerfile
      context: ./post
    ports:
      - 8080:8080
    networks:
      - app-network
    env_file:
      - .env.production
    depends_on:
      - post-db
  
  web:
    container_name: web
    build:
      dockerfile: Dockerfile
      context: ./web
    ports: 
      - 3000:80