name: CI web

on:
  push:
    branches: [ dev, prod ]

jobs:

  update-server:
    name: Update Server docker image
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Set Production Env variables if prod is target
        if: ${{ steps.extract_branch.outputs.branch == 'prod' }}
        run: |
          echo "VM_IP=$PROD_IP" >> $GITHUB_ENV && echo "VM_USER=$PROD_USER" >> $GITHUB_ENV
        env:
          PROD_IP: ${{ secrets.PROD_IP }}
          PROD_USER: ${{ secrets.PROD_USER }}
      - name: Set Dev Env variables if dev is target
        if: ${{ steps.extract_branch.outputs.branch == 'dev' }}
        run: |
          echo "VM_IP=$DEV_IP" >> $GITHUB_ENV && echo "VM_USER=DEV_USER" >> $GITHUB_ENV
        env:
          DEV_IP: ${{ secrets.DEV_IP }}
          DEV_USER: ${{ secrets.DEV_USER }}
      - name: Deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /jj/jibber-jabber-infra
            docker-compose down
            echo "Server down"
            git pull
            echo "Git pull"
            docker-compose up
            echo "Server up"
          host: ${{ env.VM_IP }}
          user: ${{ env.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
